-file("c:/Program Files/erl-24.1.7/lib/parsetools-2.3.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/lexer.xrl", 48).

-file("c:/Program Files/erl-24.1.7/lib/parsetools-2.3.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/lexer.erl", 307).
yystate() -> 101.

yystate(116, [117|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 4, Tlen);
yystate(116, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(116, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,116};
yystate(115, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(114, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(114, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(114, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,114};
yystate(113, [105|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 4, Tlen);
yystate(113, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(113, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,113};
yystate(112, [101|Ics], Line, Tlen, _, _) ->
    yystate(110, Ics, Line, Tlen+1, 4, Tlen);
yystate(112, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(112, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,112};
yystate(111, [99|Ics], Line, Tlen, _, _) ->
    yystate(107, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, [97|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, [98|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(111, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,111};
yystate(110, [108|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [102|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(110, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,110};
yystate(109, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(108, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(107, [97|Ics], Line, Tlen, _, _) ->
    yystate(91, Ics, Line, Tlen+1, 4, Tlen);
yystate(107, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(107, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(107, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,107};
yystate(106, [116|Ics], Line, Tlen, _, _) ->
    yystate(116, Ics, Line, Tlen+1, 4, Tlen);
yystate(106, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(106, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(106, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,106};
yystate(105, [116|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(105, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(105, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,105};
yystate(104, [102|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(104, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,104};
yystate(103, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, [108|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 4, Tlen);
yystate(102, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,102};
yystate(101, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [74|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [70|Ics], Line, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(109, Ics, Line+1, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 69 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 73 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 75, C =< 77 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 79, C =< 83 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 85, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(101, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,101};
yystate(100, [114|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 4, Tlen);
yystate(100, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,100};
yystate(99, [106|Ics], Line, Tlen, _, _) ->
    yystate(115, Ics, Line, Tlen+1, 10, Tlen);
yystate(99, [101|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 10, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, 10, Tlen);
yystate(99, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,99};
yystate(98, [101|Ics], Line, Tlen, _, _) ->
    yystate(106, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [97|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 100 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,98};
yystate(97, [97|Ics], Line, Tlen, _, _) ->
    yystate(113, Ics, Line, Tlen+1, 4, Tlen);
yystate(97, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(97, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,97};
yystate(96, [105|Ics], Line, Tlen, _, _) ->
    yystate(104, Ics, Line, Tlen+1, 4, Tlen);
yystate(96, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,96};
yystate(95, [111|Ics], Line, Tlen, _, _) ->
    yystate(111, Ics, Line, Tlen+1, 4, Tlen);
yystate(95, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(95, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(95, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,95};
yystate(94, [111|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [109|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [110|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [108|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,94};
yystate(93, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 17, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,92};
yystate(91, [108|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(91, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,91};
yystate(90, [106|Ics], Line, Tlen, _, _) ->
    yystate(108, Ics, Line, Tlen+1, 11, Tlen);
yystate(90, [95|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 11, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(90, Ics, Line, Tlen+1, 11, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,90};
yystate(89, [122|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [121|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [115|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 120 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,89};
yystate(88, [62|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 2, Tlen);
yystate(88, [61|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 2, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,88};
yystate(87, [108|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 4, Tlen);
yystate(87, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,87};
yystate(86, [97|Ics], Line, Tlen, _, _) ->
    yystate(102, Ics, Line, Tlen+1, 4, Tlen);
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,86};
yystate(85, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(84, [110|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(84, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,84};
yystate(83, [106|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 5, Tlen);
yystate(83, [101|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 5, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(83, [46|Ics], Line, Tlen, _, _) ->
    yystate(99, Ics, Line, Tlen+1, 5, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Tlen+1, 5, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,83};
yystate(82, [122|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(82, [121|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,82};
yystate(81, [119|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [115|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [110|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 118 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,81};
yystate(80, [108|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 4, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,80};
yystate(79, [106|Ics], Line, Tlen, _, _) ->
    yystate(115, Ics, Line, Tlen+1, 10, Tlen);
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, 10, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,79};
yystate(78, [110|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 4, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,78};
yystate(77, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [105|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 4, Tlen);
yystate(76, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,76};
yystate(75, [97|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 4, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,75};
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [110|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 4, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,73};
yystate(72, [61|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 16, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,72};
yystate(71, [116|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [110|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 115 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,71};
yystate(70, [116|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 4, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,70};
yystate(69, [105|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 4, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,69};
yystate(68, [61|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, [47|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,68};
yystate(67, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(67, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,67};
yystate(66, [114|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 4, Tlen);
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,66};
yystate(65, [107|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,65};
yystate(64, [115|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,64};
yystate(63, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(63, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,63};
yystate(62, [110|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,62};
yystate(61, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line+1, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(61, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,61};
yystate(60, [61|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 2, Tlen);
yystate(60, [60|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 2, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,60};
yystate(59, [109|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 4, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,59};
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [99|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [97|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [98|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,57};
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 6, Tlen);
yystate(56, [48|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 6, Tlen);
yystate(56, [49|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 6, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,56};
yystate(55, [111|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,55};
yystate(54, [105|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,54};
yystate(53, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,53};
yystate(52, [111|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,52};
yystate(51, [106|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [101|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [46|Ics], Line, Tlen, _, _) ->
    yystate(99, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Tlen+1, 5, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,51};
yystate(50, [106|Ics], Line, Tlen, _, _) ->
    yystate(108, Ics, Line, Tlen+1, 11, Tlen);
yystate(50, [101|Ics], Line, Tlen, _, _) ->
    yystate(114, Ics, Line, Tlen+1, 11, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 11, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 11, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,50};
yystate(49, [97|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,49};
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 55 ->
    yystate(48, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,48};
yystate(47, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [111|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(44, [112|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 4, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,44};
yystate(43, [98|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 4, Tlen);
yystate(43, [97|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,43};
yystate(42, [108|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 4, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,42};
yystate(41, [101|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,41};
yystate(40, [114|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [97|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,40};
yystate(39, [114|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,39};
yystate(38, [110|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,38};
yystate(37, [108|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(35, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,35};
yystate(34, [62|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 2, Tlen);
yystate(34, [61|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 2, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,34};
yystate(33, [101|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,33};
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 8, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, 8, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(32, Ics, Line, Tlen+1, 8, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(32, Ics, Line, Tlen+1, 8, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,32};
yystate(31, [106|Ics], Line, Tlen, _, _) ->
    yystate(115, Ics, Line, Tlen+1, 10, Tlen);
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 10, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 10, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(31, Ics, Line, Tlen+1, 10, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,31};
yystate(30, [105|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,30};
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(29, Ics, Line, Tlen+1, 3, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 11 ->
    yystate(29, Ics, Line, Tlen+1, 3, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,29};
yystate(28, [117|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,28};
yystate(27, [100|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 4, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,27};
yystate(26, [117|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 4, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,26};
yystate(25, [114|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,25};
yystate(24, [105|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 4, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,24};
yystate(23, [120|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [111|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [106|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [101|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [98|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [88|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [79|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [66|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [46|Ics], Line, Tlen, _, _) ->
    yystate(99, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Tlen+1, 5, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,23};
yystate(22, [104|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,22};
yystate(21, [100|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,21};
yystate(20, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [97|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,19};
yystate(18, [101|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,18};
yystate(17, [114|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,17};
yystate(16, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [115|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,15};
yystate(14, [116|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 4, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,14};
yystate(13, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(12, [112|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 4, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,12};
yystate(11, [106|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 12, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 12, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, 12, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,11};
yystate(10, [114|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 4, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,10};
yystate(9, [115|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,9};
yystate(8, [110|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,8};
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [105|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [104|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,6};
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,5};
yystate(4, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, [115|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [110|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [109|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [102|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 108 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 114 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,3};
yystate(2, [97|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(5, Ics, Line, Tlen+1, 4, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,2};
yystate(1, [61|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 2, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,1};
yystate(0, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 55 ->
    yystate(48, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("src/lexer.xrl", 14).
yyaction_0(TokenChars, TokenLine) ->
     { token, { space, TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("src/lexer.xrl", 16).
yyaction_1(TokenChars, TokenLine) ->
     { token, { newline, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("src/lexer.xrl", 18).
yyaction_2(TokenChars, TokenLine) ->
     { token, { op, TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("src/lexer.xrl", 20).
yyaction_3(TokenChars, TokenLine) ->
     { token, { comment, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("src/lexer.xrl", 23).
yyaction_4(TokenChars, TokenLine) ->
     { token, { id, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("src/lexer.xrl", 25).
yyaction_5(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("src/lexer.xrl", 26).
yyaction_6(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("src/lexer.xrl", 27).
yyaction_7(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("src/lexer.xrl", 28).
yyaction_8(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("src/lexer.xrl", 30).
yyaction_9(TokenChars, TokenLine) ->
     { token, { keywords, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("src/lexer.xrl", 32).
yyaction_10(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("src/lexer.xrl", 33).
yyaction_11(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("src/lexer.xrl", 34).
yyaction_12(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("src/lexer.xrl", 37).
yyaction_13(TokenChars, TokenLine) ->
     { token, { imagnumber, TokenLine, TokenChars } } .

-compile({inline,yyaction_14/2}).
-file("src/lexer.xrl", 38).
yyaction_14(TokenChars, TokenLine) ->
     { token, { imagnumber, TokenLine, TokenChars } } .

-compile({inline,yyaction_15/2}).
-file("src/lexer.xrl", 39).
yyaction_15(TokenChars, TokenLine) ->
     { token, { imagnumber, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/2}).
-file("src/lexer.xrl", 42).
yyaction_16(TokenChars, TokenLine) ->
     { token, { delimiters, TokenLine, TokenChars } } .

-compile({inline,yyaction_17/2}).
-file("src/lexer.xrl", 43).
yyaction_17(TokenChars, TokenLine) ->
     { token, { delimiters, TokenLine, TokenChars } } .

-compile({inline,yyaction_18/2}).
-file("src/lexer.xrl", 44).
yyaction_18(TokenChars, TokenLine) ->
     { token, { string, TokenLine, TokenChars } } .

-file("c:/Program Files/erl-24.1.7/lib/parsetools-2.3.1/include/leexinc.hrl", 313).
